name: Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    
    - name: Install nightly for eBPF
      uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly
        components: rust-src
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          llvm \
          libelf-dev \
          libz-dev \
          pkg-config \
          linux-headers-$(uname -r)
    
    - name: Generate documentation
      run: cargo doc --no-deps --all-features
    
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        destination_dir: docs

  readme-sync:
    name: Sync README
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
    - uses: actions/checkout@v4
    
    - name: Check README consistency
      run: |
        # Check if both README files exist and are up to date
        if [ ! -f README.md ] || [ ! -f README_zh.md ]; then
          echo "Error: Both README.md and README_zh.md must exist"
          exit 1
        fi
        
        # Check if example_flamegraph.svg is referenced in both files
        if ! grep -q "example_flamegraph.svg" README.md; then
          echo "Warning: example_flamegraph.svg not found in README.md"
        fi
        
        if ! grep -q "example_flamegraph.svg" README_zh.md; then
          echo "Warning: example_flamegraph.svg not found in README_zh.md"
        fi
        
        echo "README files check completed"